name: api_hawk
description: >-
  A lightweight HTTP inspector for Flutter. Built-in support for Dio, http, and
  Chopper. Granular copy options, collapsible JSON viewer, and quick cURL export.
version: 1.0.3
homepage: https://github.com/awais-jamil/ApiHawk
repository: https://github.com/awais-jamil/ApiHawk
issue_tracker: https://github.com/awais-jamil/ApiHawk/issues
topics:
  - http
  - inspector
  - dio
  - networking
  - debugging

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  dio: '>=5.0.0 <6.0.0'
  http: '>=1.0.0 <2.0.0'
  chopper: '>=8.0.0 <9.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
